/* cellrenderertextish.h generated by valac 0.56.0, the Vala compiler, do not modify */

#ifndef __CELLRENDERERTEXTISH_H__
#define __CELLRENDERERTEXTISH_H__

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_CELL_RENDERER_TEXTISH (cell_renderer_textish_get_type ())
#define CELL_RENDERER_TEXTISH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CELL_RENDERER_TEXTISH, CellRendererTextish))
#define CELL_RENDERER_TEXTISH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CELL_RENDERER_TEXTISH, CellRendererTextishClass))
#define IS_CELL_RENDERER_TEXTISH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CELL_RENDERER_TEXTISH))
#define IS_CELL_RENDERER_TEXTISH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CELL_RENDERER_TEXTISH))
#define CELL_RENDERER_TEXTISH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CELL_RENDERER_TEXTISH, CellRendererTextishClass))

typedef struct _CellRendererTextish CellRendererTextish;
typedef struct _CellRendererTextishClass CellRendererTextishClass;
typedef struct _CellRendererTextishPrivate CellRendererTextishPrivate;
typedef enum  {
	CELL_RENDERER_TEXTISH_MODE_Text,
	CELL_RENDERER_TEXTISH_MODE_Key,
	CELL_RENDERER_TEXTISH_MODE_Popup,
	CELL_RENDERER_TEXTISH_MODE_Combo
} CellRendererTextishMode;

#define CELL_RENDERER_TEXTISH_TYPE_MODE (cell_renderer_textish_mode_get_type ())

struct _CellRendererTextish {
	GtkCellRendererText parent_instance;
	CellRendererTextishPrivate * priv;
	CellRendererTextishMode mode;
	gchar** items;
	gint items_length1;
};

struct _CellRendererTextishClass {
	GtkCellRendererTextClass parent_class;
};

VALA_EXTERN GType cell_renderer_textish_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (CellRendererTextish, g_object_unref)
VALA_EXTERN GType cell_renderer_textish_mode_get_type (void) G_GNUC_CONST ;
VALA_EXTERN CellRendererTextish* cell_renderer_textish_new (void);
VALA_EXTERN CellRendererTextish* cell_renderer_textish_construct (GType object_type);
VALA_EXTERN CellRendererTextish* cell_renderer_textish_new_with_items (gchar** items,
                                                           gint items_length1);
VALA_EXTERN CellRendererTextish* cell_renderer_textish_construct_with_items (GType object_type,
                                                                 gchar** items,
                                                                 gint items_length1);
VALA_EXTERN void cell_renderer_textish_set_items (CellRendererTextish* self,
                                      gchar** items_,
                                      gint items__length1);
VALA_EXTERN GdkPixbuf* cell_renderer_textish_get_icon (CellRendererTextish* self);
VALA_EXTERN void cell_renderer_textish_set_icon (CellRendererTextish* self,
                                     GdkPixbuf* value);

G_END_DECLS

#endif
